name: daily_wash
description: A new Flutter project.

publish_to: 'none'

version: 1.1.2+8

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  flutter_bloc: ^8.0.1
  conditional_builder_null_safety: ^0.0.6
  easy_localization: ^3.0.1
  internet_connection_checker: ^0.0.1+4
  image_picker: ^1.0.5
  fluttertoast: ^8.0.8
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  new_version_plus: ^0.0.10
  geolocator: ^9.0.2
  url_launcher: ^6.0.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.2.1
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  gap: ^3.0.1
  toastification: ^1.2.0
  flutter_html: ^3.0.0-beta.2
  map_launcher: ^3.1.0
  permission_handler: ^11.2.0
  geocoding: ^2.0.2
  path_provider: ^2.0.11
  screenshot: ^2.1.0
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  firebase_remote_config: ^4.3.8
  package_info_plus: ^4.0.2








dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  remove_alpha_ios: true

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/
    - assets/langs/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf

