// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyApOW4SKZWfgHfnzbPsdLiD20LLOyYwu8I',
      appId: '1:637468107690:android:297439618bee92cd5ec1d3',
      messagingSenderId: '637468107690',
      projectId: 'dailywash-67f79',
      storageBucket: 'dailywash-67f79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyDBdSHEbpLRUB8_831XwqDYQWpu2jieyzs',
      appId: '1:637468107690:ios:e6194f82527d56fc5ec1d3',
      messagingSenderId: '637468107690',
      projectId: 'dailywash-67f79',
      storageBucket: 'dailywash-67f79.appspot.com',
      iosBundleId: 'com.DailyWashDelivry',
  );

}
